
var effects = require('./effects');
var envelope = require('./envelope');
var lfo = require('./lfo');
var macro = require('./macro');
var mod = require('./mod');

module.exports = {
  midiNRPNs: {
    ...envelope,
    ...lfo,
    ...effects,
    ...macro.knob1,
    ...macro.knob2,
    ...macro.knob3,
    ...macro.knob4,
    ...macro.knob5,
    ...macro.knob6,
    ...macro.knob7,
    ...macro.knob8,
    ...mod.matrix1,
    ...mod.matrix2,
    ...mod.matrix3,
    ...mod.matrix4,
    ...mod.matrix5,
    ...mod.matrix6,
    ...mod.matrix7,
    ...mod.matrix8,
    ...mod.matrix9,
    ...mod.matrix10,
    ...mod.matrix11,
    ...mod.matrix12,
    ...mod.matrix13,
    ...mod.matrix14,
    ...mod.matrix15,
    ...mod.matrix16,
    ...mod.matrix17,
    ...mod.matrix18,
    ...mod.matrix19,
    ...mod.matrix20,
  },
  midiComponents: {
    'envelope': Object.keys(envelope),
    'lfo': Object.keys(lfo),
    'effects': Object.keys(effects),
    'macro knob 1': Object.keys(macro.knob1),
    'macro knob 2': Object.keys(macro.knob2),
    'macro knob 3': Object.keys(macro.knob3),
    'macro knob 4': Object.keys(macro.knob4),
    'macro knob 5': Object.keys(macro.knob5),
    'macro knob 6': Object.keys(macro.knob6),
    'macro knob 7': Object.keys(macro.knob7),
    'macro knob 8': Object.keys(macro.knob8),
    'mod matrix 1': Object.keys(mod.matrix1),
    'mod matrix 2': Object.keys(mod.matrix2),
    'mod matrix 3': Object.keys(mod.matrix3),
    'mod matrix 4': Object.keys(mod.matrix4),
    'mod matrix 5': Object.keys(mod.matrix5),
    'mod matrix 6': Object.keys(mod.matrix6),
    'mod matrix 7': Object.keys(mod.matrix7),
    'mod matrix 8': Object.keys(mod.matrix8),
    'mod matrix 9': Object.keys(mod.matrix9),
    'mod matrix 10': Object.keys(mod.matrix10),
    'mod matrix 11': Object.keys(mod.matrix11),
    'mod matrix 12': Object.keys(mod.matrix12),
    'mod matrix 13': Object.keys(mod.matrix13),
    'mod matrix 14': Object.keys(mod.matrix14),
    'mod matrix 15': Object.keys(mod.matrix15),
    'mod matrix 16': Object.keys(mod.matrix16),
    'mod matrix 17': Object.keys(mod.matrix17),
    'mod matrix 18': Object.keys(mod.matrix18),
    'mod matrix 19': Object.keys(mod.matrix19),
    'mod matrix 20': Object.keys(mod.matrix20),
  }
};